<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ClinicCommunicationMasterTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('ClinicCommunicationMaster')->delete();
        
        \DB::table('ClinicCommunicationMaster')->insert(array (
            0 => 
            array (
                'ClinicCommunicationMasterID' => '92B13E97-7040-48C6-8BB6-03B6942B61AC',
                'CommunicationMasterTypeID' => '1',
                'CommunicationMasterSubTypeID' => '1',
                'CommunicationMasterSubTypeCode' => 'RoutineSMS_AUTO_DaysReminder1',
                'Category' => 'Routine_Reminder',
                'Description' => 'Anual Routine Reminder',
                'CommunicationExecutionType' => '1',
                'Attribute1' => 'Days',
                'DefaultAttributeValue1' => '365',
                'Attribute2' => 'Scheduled Time',
                'DefaultAttributeValue2' => '07:00',
                'CreatedOn' => '2013-12-18 15:00:18.020',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 15:00:18.020',
                'LastUpdatedBy' => 'ABhishek',
            ),
            1 => 
            array (
                'ClinicCommunicationMasterID' => 'C6E205B4-A7A6-4F1B-BBF4-070A02FE0463',
                'CommunicationMasterTypeID' => '1',
                'CommunicationMasterSubTypeID' => '6',
                'CommunicationMasterSubTypeCode' => 'RoutineSMS_AUTO_IncompleteTreatmentReminder',
                'Category' => 'Routine_Reminder',
                'Description' => 'InComplete Treatment Reminder',
                'CommunicationExecutionType' => '1',
                'Attribute1' => 'Days',
                'DefaultAttributeValue1' => '30',
                'Attribute2' => 'Scheduled Time',
                'DefaultAttributeValue2' => '07:00',
                'CreatedOn' => '2013-12-18 15:00:18.020',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 15:00:18.020',
                'LastUpdatedBy' => 'ABhishek',
            ),
            2 => 
            array (
                'ClinicCommunicationMasterID' => 'E6AAA834-F725-4CBB-BA6A-271F22544D86',
                'CommunicationMasterTypeID' => '1',
                'CommunicationMasterSubTypeID' => '17',
                'CommunicationMasterSubTypeCode' => 'AppointmentSMS_MANUAL_Patient_Doctor_CancelApt',
                'Category' => 'Appointment',
            'Description' => 'Appointment  Cancelled(Doctor and Patient)',
                'CommunicationExecutionType' => '2',
                'Attribute1' => '',
                'DefaultAttributeValue1' => NULL,
                'Attribute2' => '',
                'DefaultAttributeValue2' => NULL,
                'CreatedOn' => '2013-12-18 15:00:18.020',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 15:00:18.020',
                'LastUpdatedBy' => 'ABhishek',
            ),
            3 => 
            array (
                'ClinicCommunicationMasterID' => 'DB9EBE03-ECC6-4643-81D8-38533A43EE8C',
                'CommunicationMasterTypeID' => '1',
                'CommunicationMasterSubTypeID' => '19',
                'CommunicationMasterSubTypeCode' => 'AppointmentSMS_MANUAL_DoctorCancelApt',
                'Category' => 'Appointment',
            'Description' => 'Appointment  Cancelled(Doctor Notification)',
                'CommunicationExecutionType' => '2',
                'Attribute1' => '',
                'DefaultAttributeValue1' => NULL,
                'Attribute2' => '',
                'DefaultAttributeValue2' => NULL,
                'CreatedOn' => '2013-12-18 15:00:18.020',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 15:00:18.020',
                'LastUpdatedBy' => 'ABhishek',
            ),
            4 => 
            array (
                'ClinicCommunicationMasterID' => '60E61AA4-5B53-4906-B7EC-38854A4E2F84',
                'CommunicationMasterTypeID' => '1',
                'CommunicationMasterSubTypeID' => '22',
                'CommunicationMasterSubTypeCode' => 'WaitingAreaSMS_AUTO_CheckOutThankYou',
                'Category' => 'Waiting_Area',
            'Description' => 'Waiting Area Thank you (check out)',
                'CommunicationExecutionType' => '1',
                'Attribute1' => '',
                'DefaultAttributeValue1' => NULL,
                'Attribute2' => 'Scheduled Time',
                'DefaultAttributeValue2' => '20:00',
                'CreatedOn' => '2013-12-18 15:00:18.020',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 15:00:18.020',
                'LastUpdatedBy' => 'ABhishek',
            ),
            5 => 
            array (
                'ClinicCommunicationMasterID' => '631C9310-1ADC-413E-B443-4831BF41B072',
                'CommunicationMasterTypeID' => '1',
                'CommunicationMasterSubTypeID' => '9',
                'CommunicationMasterSubTypeCode' => 'AppointmentSMS_AUTO_PatientHoursBefore',
                'Category' => 'Appointment',
            'Description' => 'Appointment 1 Hour before (Patient Reminder)',
                'CommunicationExecutionType' => '1',
                'Attribute1' => 'Hours',
                'DefaultAttributeValue1' => '1',
                'Attribute2' => '',
                'DefaultAttributeValue2' => NULL,
                'CreatedOn' => '2013-12-18 15:00:18.020',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 15:00:18.020',
                'LastUpdatedBy' => 'ABhishek',
            ),
            6 => 
            array (
                'ClinicCommunicationMasterID' => '5BFE7BE7-9987-4F85-AF33-4B650336F550',
                'CommunicationMasterTypeID' => '1',
                'CommunicationMasterSubTypeID' => '27',
                'CommunicationMasterSubTypeCode' => 'PaymentSMS_AUTO_Recieved',
                'Category' => 'Payments',
                'Description' => 'Payment Recieved',
                'CommunicationExecutionType' => '1',
                'Attribute1' => '',
                'DefaultAttributeValue1' => NULL,
                'Attribute2' => 'Scheduled Time',
                'DefaultAttributeValue2' => '20:00',
                'CreatedOn' => '2013-12-18 15:00:18.020',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 15:00:18.020',
                'LastUpdatedBy' => 'ABhishek',
            ),
            7 => 
            array (
                'ClinicCommunicationMasterID' => '04FC5BA4-C780-4199-A32C-62B0D6ED2E15',
                'CommunicationMasterTypeID' => '1',
                'CommunicationMasterSubTypeID' => '24',
                'CommunicationMasterSubTypeCode' => 'PaymentSMS_AUTO_OutstandingDuration_Reminder1',
                'Category' => 'Payments',
                'Description' => 'Payment 1 Week Outsatnding Reminder',
                'CommunicationExecutionType' => '1',
                'Attribute1' => 'Days',
                'DefaultAttributeValue1' => '7',
                'Attribute2' => 'Scheduled Time',
                'DefaultAttributeValue2' => '07:00',
                'CreatedOn' => '2013-12-18 15:00:18.020',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 15:00:18.020',
                'LastUpdatedBy' => 'ABhishek',
            ),
            8 => 
            array (
                'ClinicCommunicationMasterID' => '07BAD59D-C991-47C5-96CC-63F721ECE43F',
                'CommunicationMasterTypeID' => '1',
                'CommunicationMasterSubTypeID' => '30',
                'CommunicationMasterSubTypeCode' => 'SubscriberSMS_AUTO_Moring',
                'Category' => 'Scheduler',
                'Description' => 'Subscriber Morning Notification',
                'CommunicationExecutionType' => '1',
                'Attribute1' => '',
                'DefaultAttributeValue1' => NULL,
                'Attribute2' => 'Scheduled Time',
                'DefaultAttributeValue2' => '07:00',
                'CreatedOn' => '2013-12-18 15:00:18.020',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 15:00:18.020',
                'LastUpdatedBy' => 'ABhishek',
            ),
            9 => 
            array (
                'ClinicCommunicationMasterID' => 'AB77B37C-7ACB-4A55-BDC8-686C6D70BC9F',
                'CommunicationMasterTypeID' => '1',
                'CommunicationMasterSubTypeID' => '25',
                'CommunicationMasterSubTypeCode' => 'PaymentSMS_AUTO_OutstandingDuration_Reminder2',
                'Category' => 'Payments',
                'Description' => 'Payment 1 Month Outsatnding Reminder',
                'CommunicationExecutionType' => '1',
                'Attribute1' => 'Days',
                'DefaultAttributeValue1' => '30',
                'Attribute2' => 'Scheduled Time',
                'DefaultAttributeValue2' => '07:00',
                'CreatedOn' => '2013-12-18 15:00:18.020',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 15:00:18.020',
                'LastUpdatedBy' => 'ABhishek',
            ),
            10 => 
            array (
                'ClinicCommunicationMasterID' => '891E9FFE-B7EB-4E6F-BCC8-6B3C8C95704E',
                'CommunicationMasterTypeID' => '1',
                'CommunicationMasterSubTypeID' => '29',
                'CommunicationMasterSubTypeCode' => 'EcgTRAISMS_MANUAL_OptOutSubscriber',
                'Category' => 'EcgTRAI',
                'Description' => 'TRAI Opt-Out SMS',
                'CommunicationExecutionType' => '2',
                'Attribute1' => '',
                'DefaultAttributeValue1' => NULL,
                'Attribute2' => '',
                'DefaultAttributeValue2' => NULL,
                'CreatedOn' => '2013-12-18 15:00:18.020',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 15:00:18.020',
                'LastUpdatedBy' => 'ABhishek',
            ),
            11 => 
            array (
                'ClinicCommunicationMasterID' => '1CB582F2-1154-4B61-814D-6CBB6E809693',
                'CommunicationMasterTypeID' => '1',
                'CommunicationMasterSubTypeID' => '23',
                'CommunicationMasterSubTypeCode' => 'PrescriptionSMS_MANUAL_Details',
                'Category' => 'Prescription',
                'Description' => 'Prescription Details',
                'CommunicationExecutionType' => '2',
                'Attribute1' => '',
                'DefaultAttributeValue1' => NULL,
                'Attribute2' => '',
                'DefaultAttributeValue2' => NULL,
                'CreatedOn' => '2013-12-18 15:00:18.020',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 15:00:18.020',
                'LastUpdatedBy' => 'ABhishek',
            ),
            12 => 
            array (
                'ClinicCommunicationMasterID' => '1D51DBB2-D3EF-4E68-9E8B-6D4F47825E76',
                'CommunicationMasterTypeID' => '1',
                'CommunicationMasterSubTypeID' => '7',
                'CommunicationMasterSubTypeCode' => 'AppointmentSMS_AUTO_PatientMorning',
                'Category' => 'Appointment',
            'Description' => 'Appointment Morning (Patient Reminder)',
                'CommunicationExecutionType' => '1',
                'Attribute1' => '',
                'DefaultAttributeValue1' => NULL,
                'Attribute2' => 'Scheduled Time',
                'DefaultAttributeValue2' => '07:00',
                'CreatedOn' => '2013-12-18 15:00:18.020',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 15:00:18.020',
                'LastUpdatedBy' => 'ABhishek',
            ),
            13 => 
            array (
                'ClinicCommunicationMasterID' => '60063E58-4633-4C37-A3E8-6ECF43428278',
                'CommunicationMasterTypeID' => '2',
                'CommunicationMasterSubTypeID' => '2',
                'CommunicationMasterSubTypeCode' => 'Custom_EMail',
                'Category' => 'Custom',
                'Description' => 'Custom Email',
                'CommunicationExecutionType' => '2',
                'Attribute1' => '',
                'DefaultAttributeValue1' => NULL,
                'Attribute2' => '',
                'DefaultAttributeValue2' => NULL,
                'CreatedOn' => '2013-12-18 15:10:54.187',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 15:10:54.187',
                'LastUpdatedBy' => 'ABhishek',
            ),
            14 => 
            array (
                'ClinicCommunicationMasterID' => 'DFDFD7FB-7F88-4210-99CF-874FDA1FFA37',
                'CommunicationMasterTypeID' => '1',
                'CommunicationMasterSubTypeID' => '2',
                'CommunicationMasterSubTypeCode' => 'RoutineSMS_AUTO_DaysReminder2',
                'Category' => 'Routine_Reminder',
                'Description' => 'Half Yearly Routine Reminder',
                'CommunicationExecutionType' => '1',
                'Attribute1' => 'Days',
                'DefaultAttributeValue1' => '186',
                'Attribute2' => 'Scheduled Time',
                'DefaultAttributeValue2' => '07:00',
                'CreatedOn' => '2013-12-18 15:00:18.020',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 15:00:18.020',
                'LastUpdatedBy' => 'ABhishek',
            ),
            15 => 
            array (
                'ClinicCommunicationMasterID' => '33649D00-2ED1-4C3C-84F5-940FCEB4F4C1',
                'CommunicationMasterTypeID' => '1',
                'CommunicationMasterSubTypeID' => '14',
                'CommunicationMasterSubTypeCode' => 'AppointmentSMS_MANUAL_Patient_Doctor_ReScheduleApt',
                'Category' => 'Appointment',
            'Description' => 'Appointment  Rescheduled (Doctor and Patient)',
                'CommunicationExecutionType' => '2',
                'Attribute1' => '',
                'DefaultAttributeValue1' => NULL,
                'Attribute2' => '',
                'DefaultAttributeValue2' => NULL,
                'CreatedOn' => '2013-12-18 15:00:18.020',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 15:00:18.020',
                'LastUpdatedBy' => 'ABhishek',
            ),
            16 => 
            array (
                'ClinicCommunicationMasterID' => '92E256EE-B3C2-40E6-8D21-94A30DBC6A11',
                'CommunicationMasterTypeID' => '1',
                'CommunicationMasterSubTypeID' => '8',
                'CommunicationMasterSubTypeCode' => 'AppointmentSMS_AUTO_PatientNight',
                'Category' => 'Appointment',
            'Description' => 'Appointment Night (Patient Reminder)',
                'CommunicationExecutionType' => '1',
                'Attribute1' => '',
                'DefaultAttributeValue1' => NULL,
                'Attribute2' => 'Scheduled Time',
                'DefaultAttributeValue2' => '20:00',
                'CreatedOn' => '2013-12-18 15:00:18.020',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 15:00:18.020',
                'LastUpdatedBy' => 'ABhishek',
            ),
            17 => 
            array (
                'ClinicCommunicationMasterID' => '04D87682-10E9-4E59-A5D0-965C70CA96C3',
                'CommunicationMasterTypeID' => '1',
                'CommunicationMasterSubTypeID' => '21',
                'CommunicationMasterSubTypeCode' => 'WaitingAreaSMS_AUTO_QueueCountNotification',
                'Category' => 'Waiting_Area',
                'Description' => 'Waiting Area Queue Count Notification',
                'CommunicationExecutionType' => '1',
                'Attribute1' => 'QueueCount',
                'DefaultAttributeValue1' => '5',
                'Attribute2' => '',
                'DefaultAttributeValue2' => NULL,
                'CreatedOn' => '2013-12-18 15:00:18.020',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 15:00:18.020',
                'LastUpdatedBy' => 'ABhishek',
            ),
            18 => 
            array (
                'ClinicCommunicationMasterID' => 'B42F8198-FF70-4F73-9B51-9D8EAAC87DDE',
                'CommunicationMasterTypeID' => '2',
                'CommunicationMasterSubTypeID' => '1',
                'CommunicationMasterSubTypeCode' => 'Auto_EMail',
                'Category' => 'Auto_EMail',
                'Description' => 'Auto Email',
                'CommunicationExecutionType' => '1',
                'Attribute1' => '',
                'DefaultAttributeValue1' => NULL,
                'Attribute2' => 'Scheduled Time',
                'DefaultAttributeValue2' => NULL,
                'CreatedOn' => '2013-12-18 15:10:54.187',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 15:10:54.187',
                'LastUpdatedBy' => 'ABhishek',
            ),
            19 => 
            array (
                'ClinicCommunicationMasterID' => 'C9456089-C4F2-4EC9-9FFA-A8503B8C39D0',
                'CommunicationMasterTypeID' => '1',
                'CommunicationMasterSubTypeID' => '28',
                'CommunicationMasterSubTypeCode' => 'EcgTRAISMS_MANUAL_OptInSubscriber',
                'Category' => 'EcgTRAI',
                'Description' => 'TRAI Opt-In SMS',
                'CommunicationExecutionType' => '2',
                'Attribute1' => '',
                'DefaultAttributeValue1' => NULL,
                'Attribute2' => '',
                'DefaultAttributeValue2' => NULL,
                'CreatedOn' => '2013-12-18 15:00:18.020',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 15:00:18.020',
                'LastUpdatedBy' => 'ABhishek',
            ),
            20 => 
            array (
                'ClinicCommunicationMasterID' => '7A718F12-E067-4958-BFAD-B2AE316D3458',
                'CommunicationMasterTypeID' => '1',
                'CommunicationMasterSubTypeID' => '13',
                'CommunicationMasterSubTypeCode' => 'AppointmentSMS_MANUAL_DoctorNewApt',
                'Category' => 'Appointment',
            'Description' => 'New Appointment (Doctor Notification)',
                'CommunicationExecutionType' => '2',
                'Attribute1' => '',
                'DefaultAttributeValue1' => NULL,
                'Attribute2' => '',
                'DefaultAttributeValue2' => NULL,
                'CreatedOn' => '2013-12-18 15:00:18.020',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 15:00:18.020',
                'LastUpdatedBy' => 'ABhishek',
            ),
            21 => 
            array (
                'ClinicCommunicationMasterID' => '91E5C37D-3D27-422A-8308-C03784E60599',
                'CommunicationMasterTypeID' => '1',
                'CommunicationMasterSubTypeID' => '12',
                'CommunicationMasterSubTypeCode' => 'AppointmentSMS_MANUAL_PatientNewApt',
                'Category' => 'Appointment',
            'Description' => 'New Appointment (Patient Notification)',
                'CommunicationExecutionType' => '2',
                'Attribute1' => '',
                'DefaultAttributeValue1' => NULL,
                'Attribute2' => '',
                'DefaultAttributeValue2' => NULL,
                'CreatedOn' => '2013-12-18 15:00:18.020',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 15:00:18.020',
                'LastUpdatedBy' => 'ABhishek',
            ),
            22 => 
            array (
                'ClinicCommunicationMasterID' => '40F4715C-5611-428D-BADE-C41A4BD8673D',
                'CommunicationMasterTypeID' => '1',
                'CommunicationMasterSubTypeID' => '16',
                'CommunicationMasterSubTypeCode' => 'AppointmentSMS_MANUAL_DoctorReScheduleApt',
                'Category' => 'Appointment',
            'Description' => 'Appointment  Rescheduled (Doctor Notification)',
                'CommunicationExecutionType' => '2',
                'Attribute1' => '',
                'DefaultAttributeValue1' => NULL,
                'Attribute2' => '',
                'DefaultAttributeValue2' => NULL,
                'CreatedOn' => '2013-12-18 15:00:18.020',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 15:00:18.020',
                'LastUpdatedBy' => 'ABhishek',
            ),
            23 => 
            array (
                'ClinicCommunicationMasterID' => '4B2EA5C0-250C-4826-98E4-C7350F25A406',
                'CommunicationMasterTypeID' => '1',
                'CommunicationMasterSubTypeID' => '11',
                'CommunicationMasterSubTypeCode' => 'AppointmentSMS_MANUAL_Patient_Doctor_NewApt',
                'Category' => 'Appointment',
            'Description' => 'New Appointment (Doctor and Patient)',
                'CommunicationExecutionType' => '2',
                'Attribute1' => '',
                'DefaultAttributeValue1' => NULL,
                'Attribute2' => '',
                'DefaultAttributeValue2' => NULL,
                'CreatedOn' => '2013-12-18 15:00:18.020',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 15:00:18.020',
                'LastUpdatedBy' => 'ABhishek',
            ),
            24 => 
            array (
                'ClinicCommunicationMasterID' => '9D536206-8E74-4929-8F92-C9F8615538EF',
                'CommunicationMasterTypeID' => '1',
                'CommunicationMasterSubTypeID' => '20',
                'CommunicationMasterSubTypeCode' => 'WaitingAreaSMS_MANUAL_TokenNumber',
                'Category' => 'Waiting_Area',
                'Description' => 'Waiting Area Token Number',
                'CommunicationExecutionType' => '2',
                'Attribute1' => '',
                'DefaultAttributeValue1' => NULL,
                'Attribute2' => '',
                'DefaultAttributeValue2' => NULL,
                'CreatedOn' => '2013-12-18 15:00:18.020',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 15:00:18.020',
                'LastUpdatedBy' => 'ABhishek',
            ),
            25 => 
            array (
                'ClinicCommunicationMasterID' => 'F4C00C70-9292-4164-B681-CCC07D58CC9F',
                'CommunicationMasterTypeID' => '1',
                'CommunicationMasterSubTypeID' => '26',
                'CommunicationMasterSubTypeCode' => 'PaymentSMS_AUTO_OutstandingDuration_Reminder3',
                'Category' => 'Payments',
                'Description' => 'Payment 3 Months Outsatnding Reminder',
                'CommunicationExecutionType' => '1',
                'Attribute1' => 'Days',
                'DefaultAttributeValue1' => '90',
                'Attribute2' => 'Scheduled Time',
                'DefaultAttributeValue2' => '07:00',
                'CreatedOn' => '2013-12-18 15:00:18.020',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 15:00:18.020',
                'LastUpdatedBy' => 'ABhishek',
            ),
            26 => 
            array (
                'ClinicCommunicationMasterID' => '7D705218-9F1E-478E-9371-D047FE49BD14',
                'CommunicationMasterTypeID' => '1',
                'CommunicationMasterSubTypeID' => '31',
                'CommunicationMasterSubTypeCode' => 'SubscriberSMS_AUTO_Night',
                'Category' => 'Scheduler',
                'Description' => 'Subscriber Night Notification',
                'CommunicationExecutionType' => '1',
                'Attribute1' => '',
                'DefaultAttributeValue1' => NULL,
                'Attribute2' => 'Scheduled Time',
                'DefaultAttributeValue2' => '19:00',
                'CreatedOn' => '2013-12-18 15:00:18.020',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 15:00:18.020',
                'LastUpdatedBy' => 'ABhishek',
            ),
            27 => 
            array (
                'ClinicCommunicationMasterID' => 'DED97604-A424-44D5-B8A4-DFD1C1A3832D',
                'CommunicationMasterTypeID' => '1',
                'CommunicationMasterSubTypeID' => '5',
                'CommunicationMasterSubTypeCode' => 'RoutineSMS_AUTO_DaysReminder5',
                'Category' => 'Routine_Reminder',
                'Description' => 'Weekly Routine Reminder',
                'CommunicationExecutionType' => '1',
                'Attribute1' => 'Days',
                'DefaultAttributeValue1' => '7',
                'Attribute2' => 'Scheduled Time',
                'DefaultAttributeValue2' => '07:00',
                'CreatedOn' => '2013-12-18 15:00:18.020',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 15:00:18.020',
                'LastUpdatedBy' => 'ABhishek',
            ),
            28 => 
            array (
                'ClinicCommunicationMasterID' => '6024ED63-8902-4995-BB9D-E0C8AD60127C',
                'CommunicationMasterTypeID' => '1',
                'CommunicationMasterSubTypeID' => '15',
                'CommunicationMasterSubTypeCode' => 'AppointmentSMS_MANUAL_PatientReScheduleApt',
                'Category' => 'Appointment',
            'Description' => 'Appointment  Rescheduled (Patient Notification)',
                'CommunicationExecutionType' => '2',
                'Attribute1' => '',
                'DefaultAttributeValue1' => NULL,
                'Attribute2' => '',
                'DefaultAttributeValue2' => NULL,
                'CreatedOn' => '2013-12-18 15:00:18.020',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 15:00:18.020',
                'LastUpdatedBy' => 'ABhishek',
            ),
            29 => 
            array (
                'ClinicCommunicationMasterID' => 'B6725F62-D672-4169-AC78-E5872F1AA19F',
                'CommunicationMasterTypeID' => '1',
                'CommunicationMasterSubTypeID' => '4',
                'CommunicationMasterSubTypeCode' => 'RoutineSMS_AUTO_DaysReminder4',
                'Category' => 'Routine_Reminder',
                'Description' => 'Monthly Routine Reminder',
                'CommunicationExecutionType' => '1',
                'Attribute1' => 'Days',
                'DefaultAttributeValue1' => '30',
                'Attribute2' => 'Scheduled Time',
                'DefaultAttributeValue2' => '07:00',
                'CreatedOn' => '2013-12-18 15:00:18.020',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 15:00:18.020',
                'LastUpdatedBy' => 'ABhishek',
            ),
            30 => 
            array (
                'ClinicCommunicationMasterID' => 'D614C641-689A-49DD-A83E-E8A55B0C4575',
                'CommunicationMasterTypeID' => '1',
                'CommunicationMasterSubTypeID' => '18',
                'CommunicationMasterSubTypeCode' => 'AppointmentSMS_MANUAL_PatientCancelApt',
                'Category' => 'Appointment',
            'Description' => 'Appointment  Cancelled(Patient Notification)',
                'CommunicationExecutionType' => '2',
                'Attribute1' => '',
                'DefaultAttributeValue1' => NULL,
                'Attribute2' => '',
                'DefaultAttributeValue2' => NULL,
                'CreatedOn' => '2013-12-18 15:00:18.020',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 15:00:18.020',
                'LastUpdatedBy' => 'ABhishek',
            ),
            31 => 
            array (
                'ClinicCommunicationMasterID' => '43B9942D-00F3-4822-BCC0-F57E26B00104',
                'CommunicationMasterTypeID' => '1',
                'CommunicationMasterSubTypeID' => '10',
                'CommunicationMasterSubTypeCode' => 'AppointmentSMS_AUTO_DoctorTodaySchedule',
                'Category' => 'Appointment',
            'Description' => 'Schedule for the day (Doctor Reminder)',
                'CommunicationExecutionType' => '1',
                'Attribute1' => '',
                'DefaultAttributeValue1' => NULL,
                'Attribute2' => 'Scheduled Time',
                'DefaultAttributeValue2' => '07:00',
                'CreatedOn' => '2013-12-18 15:00:18.020',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 15:00:18.020',
                'LastUpdatedBy' => 'ABhishek',
            ),
            32 => 
            array (
                'ClinicCommunicationMasterID' => 'A5613422-9F50-4029-8EE5-FAFF6AF36C7F',
                'CommunicationMasterTypeID' => '1',
                'CommunicationMasterSubTypeID' => '33',
                'CommunicationMasterSubTypeCode' => 'EventSMS_AUTO_PatientMorning',
                'Category' => 'Events',
                'Description' => 'Event SMS to Patients',
                'CommunicationExecutionType' => '1',
                'Attribute1' => NULL,
                'DefaultAttributeValue1' => NULL,
                'Attribute2' => 'Scheduled Time',
                'DefaultAttributeValue2' => '07:00',
                'CreatedOn' => '2013-12-26 15:36:27.910',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-26 15:36:27.910',
                'LastUpdatedBy' => 'ABhishek',
            ),
            33 => 
            array (
                'ClinicCommunicationMasterID' => 'A5613422-9F50-4029-8EE5-FAFF6AF97B7F',
                'CommunicationMasterTypeID' => '1',
                'CommunicationMasterSubTypeID' => '3',
                'CommunicationMasterSubTypeCode' => 'RoutineSMS_AUTO_DaysReminder3',
                'Category' => 'Routine_Reminder',
                'Description' => 'Quaterly Routine Reminder',
                'CommunicationExecutionType' => '1',
                'Attribute1' => 'Days',
                'DefaultAttributeValue1' => '92',
                'Attribute2' => 'Scheduled Time',
                'DefaultAttributeValue2' => '07:00',
                'CreatedOn' => '2013-12-18 15:00:18.020',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 15:00:18.020',
                'LastUpdatedBy' => 'ABhishek',
            ),
            34 => 
            array (
                'ClinicCommunicationMasterID' => 'A5613422-9F50-4029-8EE5-FAFF6AF97C7F',
                'CommunicationMasterTypeID' => '1',
                'CommunicationMasterSubTypeID' => '32',
                'CommunicationMasterSubTypeCode' => 'UserSMS_Custom',
                'Category' => 'Custom',
                'Description' => 'Custom SMS',
                'CommunicationExecutionType' => '2',
                'Attribute1' => NULL,
                'DefaultAttributeValue1' => NULL,
                'Attribute2' => NULL,
                'DefaultAttributeValue2' => NULL,
                'CreatedOn' => '2013-12-18 17:03:21.633',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-18 17:03:21.633',
                'LastUpdatedBy' => 'ABhishek',
            ),
        ));
        
        
    }
}