<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SMSSituationsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('SMSSituations')->delete();
        
        \DB::table('SMSSituations')->insert(array (
            0 => 
            array (
                'SMSSituationID' => '3A72D660-9380-473B-BCA4-069B4323AF06',
                'SitutationCode' => 'SSTU025',
                'SituationDescription' => 'TRAI Opt-In SMS',
                'DetailedTrigerringDeescription' => '',
                'SituationType' => '1',
                'DependentField1' => NULL,
                'DependentField2' => NULL,
                'DependentField3' => NULL,
                'DependentField4' => NULL,
                'IsActive' => '1',
                'isDeleted' => NULL,
                'CreatedOn' => '2013-12-30 14:34:56.693',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-30 14:34:56.693',
                'LastUpdatedBy' => 'ABhishek',
            ),
            1 => 
            array (
                'SMSSituationID' => 'AD92E000-89F5-4B9E-8396-08B37664DE0B',
                'SitutationCode' => 'SSTU017',
                'SituationDescription' => 'Waiting Area Token Number',
                'DetailedTrigerringDeescription' => '',
                'SituationType' => '1',
                'DependentField1' => NULL,
                'DependentField2' => NULL,
                'DependentField3' => NULL,
                'DependentField4' => NULL,
                'IsActive' => '1',
                'isDeleted' => NULL,
                'CreatedOn' => '2013-12-30 14:34:56.693',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-30 14:34:56.693',
                'LastUpdatedBy' => 'ABhishek',
            ),
            2 => 
            array (
                'SMSSituationID' => 'EF92E001-89F5-4B9E-8396-08B37664DE0B',
                'SitutationCode' => 'SSTU029',
            'SituationDescription' => 'Waiting Area Token Number(with current status)',
                'DetailedTrigerringDeescription' => '',
                'SituationType' => '1',
                'DependentField1' => NULL,
                'DependentField2' => NULL,
                'DependentField3' => NULL,
                'DependentField4' => NULL,
                'IsActive' => '1',
                'isDeleted' => NULL,
                'CreatedOn' => '2013-12-30 14:34:56.693',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-30 14:34:56.693',
                'LastUpdatedBy' => 'ABhishek',
            ),
            3 => 
            array (
                'SMSSituationID' => '62D6C29D-86AC-430A-87D8-09CA318065EA',
                'SitutationCode' => 'SSTU015',
            'SituationDescription' => 'Appointment  Cancelled(Patient Notification)',
                'DetailedTrigerringDeescription' => '',
                'SituationType' => '1',
                'DependentField1' => NULL,
                'DependentField2' => NULL,
                'DependentField3' => NULL,
                'DependentField4' => NULL,
                'IsActive' => '1',
                'isDeleted' => NULL,
                'CreatedOn' => '2013-12-30 14:34:56.693',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-30 14:34:56.693',
                'LastUpdatedBy' => 'ABhishek',
            ),
            4 => 
            array (
                'SMSSituationID' => 'A34F8C5F-8D7C-4142-B5D1-18E92843087D',
                'SitutationCode' => 'SSTU032',
                'SituationDescription' => 'Referral Thank You sms',
                'DetailedTrigerringDeescription' => '',
                'SituationType' => '1',
                'DependentField1' => NULL,
                'DependentField2' => NULL,
                'DependentField3' => NULL,
                'DependentField4' => NULL,
                'IsActive' => '1',
                'isDeleted' => '0',
                'CreatedOn' => '2020-05-05 19:13:11.820',
                'CreatedBy' => 'System',
                'LastUpdatedOn' => '2020-05-05 19:13:11.820',
                'LastUpdatedBy' => 'System',
            ),
            5 => 
            array (
                'SMSSituationID' => 'C5FF3AAB-FFAB-4859-BC7F-1CDF56368F24',
                'SitutationCode' => 'SSTU024',
                'SituationDescription' => 'Payment Recieved',
                'DetailedTrigerringDeescription' => '',
                'SituationType' => '1',
                'DependentField1' => NULL,
                'DependentField2' => NULL,
                'DependentField3' => NULL,
                'DependentField4' => NULL,
                'IsActive' => '1',
                'isDeleted' => NULL,
                'CreatedOn' => '2013-12-30 14:34:56.693',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-30 14:34:56.693',
                'LastUpdatedBy' => 'ABhishek',
            ),
            6 => 
            array (
                'SMSSituationID' => 'EB81B9C0-73E5-4B7F-B275-1E13C5635D73',
                'SitutationCode' => 'SSTU026',
                'SituationDescription' => 'TRAI Opt-Out SMS',
                'DetailedTrigerringDeescription' => '',
                'SituationType' => '1',
                'DependentField1' => NULL,
                'DependentField2' => NULL,
                'DependentField3' => NULL,
                'DependentField4' => NULL,
                'IsActive' => '1',
                'isDeleted' => NULL,
                'CreatedOn' => '2013-12-30 14:34:56.693',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-30 14:34:56.693',
                'LastUpdatedBy' => 'ABhishek',
            ),
            7 => 
            array (
                'SMSSituationID' => '951C7C72-1950-423C-95B3-26E9114A8C80',
                'SitutationCode' => 'SSTU013',
            'SituationDescription' => 'Appointment  Rescheduled (Patient Notification)',
                'DetailedTrigerringDeescription' => '',
                'SituationType' => '1',
                'DependentField1' => NULL,
                'DependentField2' => NULL,
                'DependentField3' => NULL,
                'DependentField4' => NULL,
                'IsActive' => '1',
                'isDeleted' => NULL,
                'CreatedOn' => '2013-12-30 14:34:56.693',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-30 14:34:56.693',
                'LastUpdatedBy' => 'ABhishek',
            ),
            8 => 
            array (
                'SMSSituationID' => '09054C67-9994-4969-A573-29179A86A0FB',
                'SitutationCode' => 'SSTU027',
                'SituationDescription' => 'Birthday Greeting',
                'DetailedTrigerringDeescription' => '',
                'SituationType' => '1',
                'DependentField1' => NULL,
                'DependentField2' => NULL,
                'DependentField3' => NULL,
                'DependentField4' => NULL,
                'IsActive' => '1',
                'isDeleted' => NULL,
                'CreatedOn' => '2013-12-30 14:34:56.693',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-30 14:34:56.693',
                'LastUpdatedBy' => 'ABhishek',
            ),
            9 => 
            array (
                'SMSSituationID' => '73054C67-9994-4969-A573-29179A86A0FB',
                'SitutationCode' => 'SSTU028',
            'SituationDescription' => 'Referral Thank you(Patient)',
                'DetailedTrigerringDeescription' => '',
                'SituationType' => '1',
                'DependentField1' => NULL,
                'DependentField2' => NULL,
                'DependentField3' => NULL,
                'DependentField4' => NULL,
                'IsActive' => '1',
                'isDeleted' => NULL,
                'CreatedOn' => '2013-12-30 14:34:56.693',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-30 14:34:56.693',
                'LastUpdatedBy' => 'ABhishek',
            ),
            10 => 
            array (
                'SMSSituationID' => '731FC70E-CF48-4D8A-81A6-2E61CB76576D',
                'SitutationCode' => 'SSTU003',
                'SituationDescription' => 'Quaterly Routine Reminder',
                'DetailedTrigerringDeescription' => '',
                'SituationType' => '1',
                'DependentField1' => NULL,
                'DependentField2' => NULL,
                'DependentField3' => NULL,
                'DependentField4' => NULL,
                'IsActive' => '1',
                'isDeleted' => NULL,
                'CreatedOn' => '2013-12-30 14:34:56.693',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-30 14:34:56.693',
                'LastUpdatedBy' => 'ABhishek',
            ),
            11 => 
            array (
                'SMSSituationID' => '0FEFCE1C-24AD-410A-BBC4-2EC4F3F07B7C',
                'SitutationCode' => 'SSTU031',
                'SituationDescription' => 'Welcome message sms to patient',
                'DetailedTrigerringDeescription' => '',
                'SituationType' => '1',
                'DependentField1' => NULL,
                'DependentField2' => NULL,
                'DependentField3' => NULL,
                'DependentField4' => NULL,
                'IsActive' => '1',
                'isDeleted' => '0',
                'CreatedOn' => '2020-05-05 19:18:21.837',
                'CreatedBy' => 'System',
                'LastUpdatedOn' => '2020-05-05 19:18:21.837',
                'LastUpdatedBy' => 'System',
            ),
            12 => 
            array (
                'SMSSituationID' => '199E0B35-46F1-464C-9325-2FB61AAC182C',
                'SitutationCode' => 'SSTU006',
                'SituationDescription' => 'InComplete Treatment Reminder',
                'DetailedTrigerringDeescription' => '',
                'SituationType' => '1',
                'DependentField1' => NULL,
                'DependentField2' => NULL,
                'DependentField3' => NULL,
                'DependentField4' => NULL,
                'IsActive' => '1',
                'isDeleted' => NULL,
                'CreatedOn' => '2013-12-30 14:34:56.693',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-30 14:34:56.693',
                'LastUpdatedBy' => 'ABhishek',
            ),
            13 => 
            array (
                'SMSSituationID' => 'B360B6D1-3BE9-4772-B866-34073A51E45C',
                'SitutationCode' => 'SSTU009',
            'SituationDescription' => 'Appointment 1 Hour before (Patient Reminder)',
                'DetailedTrigerringDeescription' => '',
                'SituationType' => '1',
                'DependentField1' => NULL,
                'DependentField2' => NULL,
                'DependentField3' => NULL,
                'DependentField4' => NULL,
                'IsActive' => '1',
                'isDeleted' => NULL,
                'CreatedOn' => '2013-12-30 14:34:56.693',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-30 14:34:56.693',
                'LastUpdatedBy' => 'ABhishek',
            ),
            14 => 
            array (
                'SMSSituationID' => 'AAC329BE-4AE6-4F04-A48D-4FB26ED99E2E',
                'SitutationCode' => 'SSTU007',
            'SituationDescription' => 'Appointment Moring (Patient Reminder)',
                'DetailedTrigerringDeescription' => '',
                'SituationType' => '1',
                'DependentField1' => NULL,
                'DependentField2' => NULL,
                'DependentField3' => NULL,
                'DependentField4' => NULL,
                'IsActive' => '1',
                'isDeleted' => NULL,
                'CreatedOn' => '2013-12-30 14:34:56.693',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-30 14:34:56.693',
                'LastUpdatedBy' => 'ABhishek',
            ),
            15 => 
            array (
                'SMSSituationID' => 'BCCFD530-80CC-4748-94FF-55DBFA459EF6',
                'SitutationCode' => 'SSTU020',
                'SituationDescription' => 'Prescription Details',
                'DetailedTrigerringDeescription' => '',
                'SituationType' => '1',
                'DependentField1' => NULL,
                'DependentField2' => NULL,
                'DependentField3' => NULL,
                'DependentField4' => NULL,
                'IsActive' => '1',
                'isDeleted' => NULL,
                'CreatedOn' => '2013-12-30 14:34:56.693',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-30 14:34:56.693',
                'LastUpdatedBy' => 'ABhishek',
            ),
            16 => 
            array (
                'SMSSituationID' => 'D03AD897-3785-4B6E-803A-56AFA38BA471',
                'SitutationCode' => 'SSTU022',
                'SituationDescription' => 'Payment 1 Month Outsatnding Reminder',
                'DetailedTrigerringDeescription' => '',
                'SituationType' => '1',
                'DependentField1' => NULL,
                'DependentField2' => NULL,
                'DependentField3' => NULL,
                'DependentField4' => NULL,
                'IsActive' => '1',
                'isDeleted' => NULL,
                'CreatedOn' => '2013-12-30 14:34:56.693',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-30 14:34:56.693',
                'LastUpdatedBy' => 'ABhishek',
            ),
            17 => 
            array (
                'SMSSituationID' => '6675827B-34D0-41BC-ACCA-5FA1EA53243D',
                'SitutationCode' => 'SSTU002',
                'SituationDescription' => 'Half Yearly Routine Reminder',
                'DetailedTrigerringDeescription' => '',
                'SituationType' => '1',
                'DependentField1' => NULL,
                'DependentField2' => NULL,
                'DependentField3' => NULL,
                'DependentField4' => NULL,
                'IsActive' => '1',
                'isDeleted' => NULL,
                'CreatedOn' => '2013-12-30 14:34:56.693',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-30 14:34:56.693',
                'LastUpdatedBy' => 'ABhishek',
            ),
            18 => 
            array (
                'SMSSituationID' => 'FBAECA8A-32DF-46B9-81D7-6112D5B7B04F',
                'SitutationCode' => 'SSTU014',
            'SituationDescription' => 'Appointment  Rescheduled (Doctor Notification)',
                'DetailedTrigerringDeescription' => '',
                'SituationType' => '1',
                'DependentField1' => NULL,
                'DependentField2' => NULL,
                'DependentField3' => NULL,
                'DependentField4' => NULL,
                'IsActive' => '1',
                'isDeleted' => NULL,
                'CreatedOn' => '2013-12-30 14:34:56.693',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-30 14:34:56.693',
                'LastUpdatedBy' => 'ABhishek',
            ),
            19 => 
            array (
                'SMSSituationID' => '33ADE9D2-B599-4CF6-97D9-627D084910A9',
                'SitutationCode' => 'SSTU012',
            'SituationDescription' => 'New Appointment (Doctor Notification)',
                'DetailedTrigerringDeescription' => '',
                'SituationType' => '1',
                'DependentField1' => NULL,
                'DependentField2' => NULL,
                'DependentField3' => NULL,
                'DependentField4' => NULL,
                'IsActive' => '1',
                'isDeleted' => NULL,
                'CreatedOn' => '2013-12-30 14:34:56.693',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-30 14:34:56.693',
                'LastUpdatedBy' => 'ABhishek',
            ),
            20 => 
            array (
                'SMSSituationID' => '150D816B-736D-405D-88B5-68DF678C9CAB',
                'SitutationCode' => 'SSTU023',
                'SituationDescription' => 'Payment 3 Months Outsatnding Reminder',
                'DetailedTrigerringDeescription' => '',
                'SituationType' => '1',
                'DependentField1' => NULL,
                'DependentField2' => NULL,
                'DependentField3' => NULL,
                'DependentField4' => NULL,
                'IsActive' => '1',
                'isDeleted' => NULL,
                'CreatedOn' => '2013-12-30 14:34:56.693',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-30 14:34:56.693',
                'LastUpdatedBy' => 'ABhishek',
            ),
            21 => 
            array (
                'SMSSituationID' => '6503BB96-4745-451A-897B-6BDD3635550B',
                'SitutationCode' => 'SSTU021',
                'SituationDescription' => 'Payment 1 Week Outsatnding Reminder',
                'DetailedTrigerringDeescription' => '',
                'SituationType' => '1',
                'DependentField1' => NULL,
                'DependentField2' => NULL,
                'DependentField3' => NULL,
                'DependentField4' => NULL,
                'IsActive' => '1',
                'isDeleted' => NULL,
                'CreatedOn' => '2013-12-30 14:34:56.693',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-30 14:34:56.693',
                'LastUpdatedBy' => 'ABhishek',
            ),
            22 => 
            array (
                'SMSSituationID' => 'BA35F809-0DF1-4DF5-BB55-6E8D9DC23F1D',
                'SitutationCode' => 'SSTU018',
                'SituationDescription' => 'Waiting Area Queue Count Notification',
                'DetailedTrigerringDeescription' => '',
                'SituationType' => '1',
                'DependentField1' => NULL,
                'DependentField2' => NULL,
                'DependentField3' => NULL,
                'DependentField4' => NULL,
                'IsActive' => '1',
                'isDeleted' => NULL,
                'CreatedOn' => '2013-12-30 14:34:56.693',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-30 14:34:56.693',
                'LastUpdatedBy' => 'ABhishek',
            ),
            23 => 
            array (
                'SMSSituationID' => '9BA1121F-7A14-47A0-8C44-7B2DA174238E',
                'SitutationCode' => 'SSTU011',
            'SituationDescription' => 'New Appointment (Patient Notification)',
                'DetailedTrigerringDeescription' => '',
                'SituationType' => '1',
                'DependentField1' => NULL,
                'DependentField2' => NULL,
                'DependentField3' => NULL,
                'DependentField4' => NULL,
                'IsActive' => '1',
                'isDeleted' => NULL,
                'CreatedOn' => '2013-12-30 14:34:56.693',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-30 14:34:56.693',
                'LastUpdatedBy' => 'ABhishek',
            ),
            24 => 
            array (
                'SMSSituationID' => '320CC9CA-0AA1-4881-818E-8333206A7EE6',
                'SitutationCode' => 'SSTU010',
            'SituationDescription' => 'Schedule for the day (Doctor Reminder)',
                'DetailedTrigerringDeescription' => '',
                'SituationType' => '1',
                'DependentField1' => NULL,
                'DependentField2' => NULL,
                'DependentField3' => NULL,
                'DependentField4' => NULL,
                'IsActive' => '1',
                'isDeleted' => NULL,
                'CreatedOn' => '2013-12-30 14:34:56.693',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-30 14:34:56.693',
                'LastUpdatedBy' => 'ABhishek',
            ),
            25 => 
            array (
                'SMSSituationID' => '9AAB1022-E5F3-4F59-A3FF-8EB4D5B6CEDC',
                'SitutationCode' => 'SSTU001',
                'SituationDescription' => 'Anual Routine Reminder',
                'DetailedTrigerringDeescription' => '',
                'SituationType' => '1',
                'DependentField1' => NULL,
                'DependentField2' => NULL,
                'DependentField3' => NULL,
                'DependentField4' => NULL,
                'IsActive' => '1',
                'isDeleted' => NULL,
                'CreatedOn' => '2013-12-30 14:34:56.693',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-30 14:34:56.693',
                'LastUpdatedBy' => 'ABhishek',
            ),
            26 => 
            array (
                'SMSSituationID' => '4675811A-F2CF-43D4-92F6-8FD322F640DA',
                'SitutationCode' => 'SSTU008',
            'SituationDescription' => 'Appointment Night (Patient Reminder)',
                'DetailedTrigerringDeescription' => '',
                'SituationType' => '1',
                'DependentField1' => NULL,
                'DependentField2' => NULL,
                'DependentField3' => NULL,
                'DependentField4' => NULL,
                'IsActive' => '1',
                'isDeleted' => NULL,
                'CreatedOn' => '2013-12-30 14:34:56.693',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-30 14:34:56.693',
                'LastUpdatedBy' => 'ABhishek',
            ),
            27 => 
            array (
                'SMSSituationID' => 'C803CEBC-EB89-48AC-B3D8-95AD6937AB7E',
                'SitutationCode' => 'SSTU030',
                'SituationDescription' => 'Social media link share to Patient by sms',
                'DetailedTrigerringDeescription' => '',
                'SituationType' => '1',
                'DependentField1' => NULL,
                'DependentField2' => NULL,
                'DependentField3' => NULL,
                'DependentField4' => NULL,
                'IsActive' => '1',
                'isDeleted' => '0',
                'CreatedOn' => '2020-05-05 19:13:16.747',
                'CreatedBy' => 'System',
                'LastUpdatedOn' => '2020-05-05 19:13:16.747',
                'LastUpdatedBy' => 'System',
            ),
            28 => 
            array (
                'SMSSituationID' => 'CDE05D1F-3B21-4FCE-93E6-AC46913804EE',
                'SitutationCode' => 'SSTU005',
                'SituationDescription' => 'Weekly Routine Reminder',
                'DetailedTrigerringDeescription' => '',
                'SituationType' => '1',
                'DependentField1' => NULL,
                'DependentField2' => NULL,
                'DependentField3' => NULL,
                'DependentField4' => NULL,
                'IsActive' => '1',
                'isDeleted' => NULL,
                'CreatedOn' => '2013-12-30 14:34:56.693',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-30 14:34:56.693',
                'LastUpdatedBy' => 'ABhishek',
            ),
            29 => 
            array (
                'SMSSituationID' => '99D823E8-0E29-4196-8BED-B90625AD3CD6',
                'SitutationCode' => 'SSTU004',
                'SituationDescription' => 'Monthly Routine Reminder',
                'DetailedTrigerringDeescription' => '',
                'SituationType' => '1',
                'DependentField1' => NULL,
                'DependentField2' => NULL,
                'DependentField3' => NULL,
                'DependentField4' => NULL,
                'IsActive' => '1',
                'isDeleted' => NULL,
                'CreatedOn' => '2013-12-30 14:34:56.693',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-30 14:34:56.693',
                'LastUpdatedBy' => 'ABhishek',
            ),
            30 => 
            array (
                'SMSSituationID' => 'FF3C01A3-9158-4C6B-9415-C90368D39065',
                'SitutationCode' => 'SSTU016',
            'SituationDescription' => 'Appointment  Cancelled(Doctor Notification)',
                'DetailedTrigerringDeescription' => '',
                'SituationType' => '1',
                'DependentField1' => NULL,
                'DependentField2' => NULL,
                'DependentField3' => NULL,
                'DependentField4' => NULL,
                'IsActive' => '1',
                'isDeleted' => NULL,
                'CreatedOn' => '2013-12-30 14:34:56.693',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-30 14:34:56.693',
                'LastUpdatedBy' => 'ABhishek',
            ),
            31 => 
            array (
                'SMSSituationID' => '00583C8C-902B-47F6-8633-F1C7E26A51A2',
                'SitutationCode' => 'SSTU019',
            'SituationDescription' => 'Waiting Area Thank you (check out)',
                'DetailedTrigerringDeescription' => '',
                'SituationType' => '1',
                'DependentField1' => NULL,
                'DependentField2' => NULL,
                'DependentField3' => NULL,
                'DependentField4' => NULL,
                'IsActive' => '1',
                'isDeleted' => NULL,
                'CreatedOn' => '2013-12-30 14:34:56.693',
                'CreatedBy' => 'ABhishek',
                'LastUpdatedOn' => '2013-12-30 14:34:56.693',
                'LastUpdatedBy' => 'ABhishek',
            ),
        ));
        
        
    }
}